name: DEVELOPMENT_CI

on:
  push:
    branches: 
      - development
      - development-*
  pull_request:
    branches:
      - development
      - development-*
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: '23.x'
          elixir-version: '1.11'
      - run: mix deps.get
      - run: mix dialyzer
      - run: mix test
